[package]
name = "age"
description = "[ALPHA STATE] A simple, secure, and modern encryption tool."
version = "0.0.0"
authors = ["Jack Grigg <thestr4d@gmail.com>"]
repository = "https://github.com/str4d/rage"
readme = "README.md"
keywords = ["rage", "cli", "encryption"]
categories = ["command-line-utilities", "cryptography"]
license = "MIT OR Apache-2.0"
edition = "2018"
default-run = "rage"

[badges]
maintenance = { status = "experimental" }

[dependencies]
aead = "0.1"
base64 = "0.10"
chacha20poly1305 = "0.1"
chrono = "0.4"
console = "0.9"
cookie-factory = "0.3"
dialoguer = "0.4"
dirs = "2"
generic-array = "0.12"
getrandom = "0.1"
gumdrop = "0.6"
hkdf = "0.8"
hmac = "0.7"
man = "0.3"
minreq = { version = "1.4", features = ["https"] }
nom = "5"
scrypt = { version = "0.2", default-features = false }
sha2 = "0.8"
x25519-dalek = "0.5"
