[package]
name = "age"
description = "[ALPHA STATE] A simple, secure, and modern encryption tool."
version = "0.0.0"
authors = ["Jack Grigg <thestr4d@gmail.com>"]
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"

[badges]
maintenance = { status = "experimental" }

[dependencies]
base64 = "0.10"
chrono = "0.4"
getrandom = "0.1"
gumdrop = "0.6"
x25519-dalek = "0.5"
