[package]
name = "age"
description = "[ALPHA STATE] A simple, secure, and modern encryption tool."
version = "0.0.0"
authors = ["Jack Grigg <thestr4d@gmail.com>"]
repository = "https://github.com/str4d/rage"
readme = "README.md"
keywords = ["rage", "cli", "encryption"]
categories = ["command-line-utilities", "cryptography"]
license = "MIT OR Apache-2.0"
edition = "2018"
default-run = "rage"

[badges]
maintenance = { status = "experimental" }

[dependencies]
aead = "0.1"
base64 = "0.10"
chacha20poly1305 = "0.1"
cookie-factory = "0.3"
curve25519-dalek = "1"
generic-array = "0.12"
getrandom = "0.1"
hkdf = "0.8"
hmac = "0.7"
nom = "5"
num-bigint-dig = "0.4"
rand = "0.6"
rsa = { git = "https://github.com/lucdew/RSA", branch = "oaep" }
scrypt = { version = "0.2", default-features = false }
sha2 = "0.8"
x25519-dalek = "0.5"

# Common CLI dependencies
dialoguer = { version = "0.4", optional = true }
dirs = { version = "2", optional = true }
gumdrop = { version = "0.6", optional = true }

# rage dependencies
chrono = { version = "0.4", optional = true }
console = { version = "0.9", optional = true }
minreq = { version = "1.4", features = ["https"], optional = true }

# rage-mount dependencies
env_logger = { version = "0.7", optional = true }
fuse_mt = { version = "0.5", optional = true }
libc = { version = "0.2", optional = true }
log = { version = "0.4", optional = true }
time = { version = "0.1", optional = true }
zip = { version = "0.5", optional = true }

[dev-dependencies]
man = "0.3"

[features]
default = ["cli", "mount"]
cli-common = ["dialoguer", "dirs", "gumdrop"]
cli = ["cli-common", "chrono", "console", "minreq"]
mount = ["cli-common", "env_logger", "fuse_mt", "libc", "log", "time", "zip"]
