[package]
name = "age"
description = "[ALPHA STATE] A simple, secure, and modern encryption tool."
version = "0.0.0"
authors = ["Jack Grigg <thestr4d@gmail.com>"]
repository = "https://github.com/str4d/rage"
readme = "README.md"
keywords = ["rage", "cli", "encryption"]
categories = ["command-line-utilities", "cryptography"]
license = "MIT OR Apache-2.0"
edition = "2018"
default-run = "rage"

[badges]
maintenance = { status = "experimental" }

[dependencies]
aead = "0.1"
aes-ctr = "0.3"
base64 = "0.10"
bech32 = "0.7"
blowfish = { version = "0.4", features = ["bcrypt"] }
byteorder = "1"
chacha20poly1305 = "0.1"
cookie-factory = "0.3"
crypto-mac = "0.7"
curve25519-dalek = "2"
generic-array = "0.12"
getrandom = "0.1"
hkdf = "0.8"
hmac = "0.7"
nom = "5"
num-traits = "0.2"
pbkdf2 = "0.3"
radix64 = "0.6"
rand = "0.7"
scrypt = { version = "0.2", default-features = false }
secrecy = "0.5"
sha2 = "0.8"
x25519-dalek = "0.6"
zeroize = "1"

# Unstable dependencies
rsa = { version = "0.2", git = "https://github.com/str4d/RSA", branch = "oaep", optional = true }

# Common CLI dependencies
dialoguer = { version = "0.4", optional = true }
dirs = { version = "2", optional = true }
gumdrop = { version = "0.6", optional = true }
log = { version = "0.4", optional = true }

# rage and rage-keygen dependencies
chrono = { version = "0.4", optional = true }
console = { version = "0.9", optional = true }
minreq = { version = "1.4", features = ["https"], optional = true }

# rage-mount dependencies
env_logger = { version = "0.7", optional = true }
fuse_mt = { version = "0.5", optional = true }
libc = { version = "0.2", optional = true }
tar = { version = "0.4", optional = true }
time = { version = "0.1", optional = true }
zip = { version = "0.5", optional = true }

[dev-dependencies]
man = "0.3"
quickcheck = "0.8"
quickcheck_macros = "0.8"

[features]
default = ["cli"]
cli-common = ["dialoguer", "dirs", "gumdrop", "log"]
cli = ["cli-common", "chrono", "console", "env_logger", "minreq"]
mount = ["cli-common", "env_logger", "fuse_mt", "libc", "tar", "time", "zip"]
unstable = ["rsa"]

[[bin]]
name = "rage-mount"
required-features = ["mount"]
