[package]
name = "age-core"
description = "[BETA] Common functions used across the age crates"
version = "0.3.0"
authors = ["Jack Grigg <thestr4d@gmail.com>"]
repository = "https://github.com/str4d/rage"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
base64 = "0.11"
cookie-factory = "0.3"
nom = "5"
