name: Interoperability tests

on: push

jobs:
  build-rage:
    name: Build rage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.37.0
          override: true
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v1
        with:
          name: rage
          path: target/release/rage

  build-age:
    name: Build age
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Check out FiloSottile/age
        uses: actions/checkout@v1
        with:
          repository: FiloSottile/age
          ref: refs/heads/master
      - name: go build
        run: |
          cd $GITHUB_WORKSPACE/../age
          go build github.com/FiloSottile/age/cmd/age
      - uses: actions/upload-artifact@v1
        with:
          name: age
          path: ../age/age

  test:
    name: ${{ matrix.alice }} -> ${{ matrix.bob }}
    runs-on: ubuntu-latest
    needs: [build-rage, build-age]
    strategy:
      matrix:
        alice: [rage, age]
        bob: [rage, age]

    steps:
      - uses: actions/download-artifact@v1
        with:
          name: rage
      - uses: actions/download-artifact@v1
        with:
          name: age
      - run: chmod +x rage/rage
      - run: chmod +x age/age
      - name: Write (very not private) key
        run: echo "AGE_SECRET_KEY_CEOQVF2ZAEAYcPmOFH9huOX18t5rxBQ65L7k2WLa604" >key.txt
      - name: Pipes!
        run: echo "Test string" | ${{ matrix.alice }}/${{ matrix.alice }} pubkey:HKxueJKWOeg9GFSOJQCts45j3Zp2TTsRDfntwgSgYiI | ${{ matrix.bob }}/${{ matrix.bob }} -d key.txt | grep -q "^Test string$"
